version: "3.9"
services:
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 27017:27017
       
    volumes:
      - pgdata:/var/lib/mongo/data
    networks:
      - app_network
  
  app:
    build: .
    depends_on:
      - mongo_db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/go/src/
    networks:
      - app_network
volumes:
  pgdata:
    driver: local
  
networks:
  app_network:
    driver: bridge