version: "3.9"
services:
  rabbit:
    image: "rabbitmq:3-management"
    container_name: challenge-go-rabbitmq-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network
    
  mongo:
    image: mongo
    container_name: challenge-go-rabbitmq-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 27017:27017
    networks:
      - app_network
    
  
  app:
    build: .
    depends_on:
      - mongo
      - rabbit
    ports:
      - 5000:5000
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge
    name: app_network